//! Auto-marking keyword management and engine.
//! Keywords are stored globally in the settings table as JSON.
//! When triggered, each keyword phrase is searched in the transcript segments
//! and a point marker is created at the segment start timestamp.

use serde::{Deserialize, Serialize};
use rusqlite::Connection;
use uuid::Uuid;

/// A single keyword definition.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Keyword {
    pub id: String,
    pub phrase: String,    // text to match in transcript (case-insensitive)
    pub label: String,     // prefix for generated marker names e.g. "Auto-Mark"
}

impl Keyword {
    pub fn new(phrase: String, label: String) -> Self {
        Self { id: Uuid::new_v4().to_string(), phrase, label }
    }
}

const SETTINGS_KEY: &str = "automark_keywords";

/// Load all keywords from the settings table.
pub fn load_keywords(conn: &Connection) -> Result<Vec<Keyword>, String> {
    let result: Result<String, _> = conn.query_row(
        "SELECT value FROM settings WHERE key = ?1",
        rusqlite::params![SETTINGS_KEY],
        |row| row.get(0),
    );
    match result {
        Ok(json)                                 => serde_json::from_str(&json).map_err(|e| e.to_string()),
        Err(rusqlite::Error::QueryReturnedNoRows) => Ok(Vec::new()),
        Err(e)                                   => Err(e.to_string()),
    }
}

/// Persist all keywords to the settings table.
pub fn save_keywords(conn: &Connection, keywords: &[Keyword]) -> Result<(), String> {
    let json = serde_json::to_string(keywords).map_err(|e| e.to_string())?;
    let now  = now_secs();
    conn.execute(
        "INSERT INTO settings (key, value, updated_at) VALUES (?1, ?2, ?3)
         ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at",
        rusqlite::params![SETTINGS_KEY, json, now],
    ).map_err(|e| e.to_string())?;
    Ok(())
}

/// Result of a single auto-marking run.
#[derive(Debug, Serialize)]
pub struct AutoMarkResult {
    pub markers_created: usize,
    pub matched_keywords: Vec<String>,
}

/// Scan a transcript's segments for keyword phrases and create point markers.
///
/// - Matching is case-insensitive and exact (substring match within segment text)
/// - All matches across all keywords are collected, sorted by timestamp,
///   then numbered sequentially: "Auto-Mark 1", "Auto-Mark 2", …
/// - Any existing markers whose names start with any keyword label are removed
///   first, so re-running is idempotent
pub fn run_auto_marking(
    conn: &Connection,
    asset_id: &str,
    keywords: &[Keyword],
) -> Result<AutoMarkResult, String> {
    if keywords.is_empty() {
        return Ok(AutoMarkResult { markers_created: 0, matched_keywords: vec![] });
    }

    // Load transcript segments for this asset
    let segments_json: String = conn.query_row(
        "SELECT segments FROM transcripts WHERE asset_id = ?1",
        rusqlite::params![asset_id],
        |row| row.get(0),
    ).map_err(|_| "No transcript found for this asset. Transcribe the video first.".to_string())?;

    #[derive(Deserialize)]
    struct Segment { start_ms: i64, text: String }
    let segments: Vec<Segment> = serde_json::from_str(&segments_json)
        .map_err(|e| format!("Failed to parse segments: {}", e))?;

    // Collect all matches: (timestamp_ms, label, phrase)
    let mut matches: Vec<(i64, String, String)> = Vec::new();

    for kw in keywords {
        let phrase_lower = kw.phrase.trim().to_lowercase();
        if phrase_lower.is_empty() { continue; }

        for seg in &segments {
            if seg.text.to_lowercase().contains(&phrase_lower) {
                matches.push((seg.start_ms, kw.label.clone(), kw.phrase.clone()));
            }
        }
    }

    if matches.is_empty() {
        return Ok(AutoMarkResult { markers_created: 0, matched_keywords: vec![] });
    }

    // Sort chronologically so sequence numbers reflect video order
    matches.sort_by_key(|(ts, _, _)| *ts);

    // Remove existing auto-markers generated by any of the current keyword labels
    // so re-running is clean. We delete markers whose names start with any label.
    for kw in keywords {
        let pattern = format!("{}%", kw.label);
        conn.execute(
            "DELETE FROM markers WHERE asset_id = ?1 AND name LIKE ?2",
            rusqlite::params![asset_id, pattern],
        ).map_err(|e| e.to_string())?;
    }

    // Create one point marker per match
    let now = now_secs();
    let mut matched_phrases: Vec<String> = Vec::new();

    for (i, (start_ms, label, phrase)) in matches.iter().enumerate() {
        let marker_name = format!("{} {}", label, i + 1);
        let marker_id   = Uuid::new_v4().to_string();

        conn.execute(
            "INSERT INTO markers
               (id, asset_id, name, marker_type, position_ms, end_position_ms, created_at, updated_at)
             VALUES (?1, ?2, ?3, 'point', ?4, NULL, ?5, ?5)",
            rusqlite::params![marker_id, asset_id, marker_name, start_ms, now],
        ).map_err(|e| e.to_string())?;

        if !matched_phrases.contains(phrase) {
            matched_phrases.push(phrase.clone());
        }
    }

    Ok(AutoMarkResult {
        markers_created: matches.len(),
        matched_keywords: matched_phrases,
    })
}

fn now_secs() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as i64
}
